# Generated by Django 5.0.4 on 2024-10-17 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersmodel',
            old_name='user_id',
            new_name='id',
        ),
    ]
