# Generated by Django 5.0.4 on 2024-10-17 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_usersmodel_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='role',
            field=models.ForeignKey(db_column='role_id', default=2, on_delete=django.db.models.deletion.RESTRICT, to='api.rolesmodel'),
        ),
    ]
